name: CI

on:
  push:
    tags:
    - 'v*'

jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: |
          go build
      - uses: actions/upload-artifact@v2
        with:
          name: ssh-url-handler
          path: |
            ssh-url-handler

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          artifacts: "ssh-url-handler"
        env:
          GITHUB_TOKEN: ${{ github.token }}
