name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build ssh-url-handler
        run: |
          go build
      # - name: Create artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: ssh-url-handler
      #     path: |
      #       ssh-url-handler
      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ssh-url-handler"
          token: ${{ github.token }}
