name: CI

on:
  push:
    tags:
      - "v*"

jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build ssh-url-handler
        run: |
          go build
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          artifacts: "ssh-url-handler"
        env:
          GITHUB_TOKEN: ${{ github.token }}
