name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build ssh-url-handler
        run: go build
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "ssh-url-handler,ssh.reg"
          token: ${{ github.token }}
